package com.reunion.tirage.entity;

import org.eclipse.persistence.config.PersistenceUnitProperties;
import org.eclipse.persistence.config.SessionCustomizer;
import org.eclipse.persistence.exceptions.IntegrityChecker;
import org.eclipse.persistence.sessions.Session;

/**
 * SessionCustomizer implementation that check database integrity is DDL
 * generated by ElcipseLink. To achieve this : 
 * <li>we modify default EclipseLink
 * IntegrityCkeck options:
 * <ul>
 * <li>shouldCheckDatabase set to true</li>
 * <li>shouldCheckInstantiationPolicy set to false</li>
 * </ul>
 * </li>
 * 
 * @author PME
 * 
 */
public class SessionCustomizerImpl implements SessionCustomizer {

    @Override
    public void customize(Session session) throws Exception {
        final Object ddlGeneration = session.getProperty(PersistenceUnitProperties.DDL_GENERATION);
        // Only check schema integrity if the DDL Generation is none (or null)
        if (ddlGeneration == null || PersistenceUnitProperties.NONE.equals(ddlGeneration.toString())) {
            final IntegrityChecker ic = session.getIntegrityChecker();
            ic.setShouldCheckDatabase(true);
            ic.setShouldCheckInstantiationPolicy(false);
        }
    }
}
